#ifndef MLIR_DIALECT_LLHD_LLHDOPS_H
#define MLIR_DIALECT_LLHD_LLHDOPS_H

#include "mlir/Dialect/LLHD/LLHDDialect.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"

namespace mlir {
namespace llhd {
/// Retrieve the class declarations generated by TableGen
#define GET_OP_CLASSES
#include "mlir/Dialect/LLHD/LLHDOps.h.inc"
} // namespace llhd
} // namespace mlir

#endif // MLIR_DIALECT_LLHD_LLHDOPS_H
